name: MacOS C Build CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: xmake
        run: xmake
